# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kyX4V8uiJ69R1_Yz2Fhuyw-wT0SWOrBy
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


import warnings
warnings.filterwarnings('ignore')


plt.style.use("fivethirtyeight")
# %matplotlib inline

df=pd.read_csv('/content/Iris.csv')
df.head()

#information about the dataset
df.info()

#describing about the dataset
df.describe()

df.shape

df.drop('Id',axis=1,inplace=True)

df.head()

df['Species'].value_counts()

#finding the null value
df.isnull().sum()

import missingno as msno
msno.bar(df)

df.drop_duplicates(inplace=True)

""" Relationship between species and sepal length"""

plt.figure(figsize=(15,8))
sns.boxplot(x='Species',y='SepalLengthCm',data=df.sort_values('SepalLengthCm',ascending=False))

df.plot(kind='scatter',x='SepalWidthCm',y='SepalLengthCm')

"""Relationship between sepal width and sepal length"""

sns.jointplot(x="SepalLengthCm", y="SepalWidthCm", data=df, size=5)

"""Pairplot"""

sns.pairplot(df, hue="Species", size=3)

"""5. Boxplot"""

df.boxplot(by="Species", figsize=(12, 6))

""" Andrews_curves"""

import pandas.plotting
from pandas.plotting import andrews_curves
andrews_curves(df, "Species")

""".CategoricalPlot"""

plt.figure(figsize=(15,15))
sns.catplot(x='Species',y='SepalWidthCm',data=df.sort_values('SepalWidthCm',ascending=False),kind='boxen')

"""voillin plot"""

plt.figure(figsize=(15,10))
plt.subplot(2,2,1)
sns.violinplot(x='Species',y='PetalLengthCm',data=df)
plt.subplot(2,2,2)
sns.violinplot(x='Species',y='PetalWidthCm',data=df)
plt.subplot(2,2,3)
sns.violinplot(x='Species',y='SepalLengthCm',data=df)
plt.subplot(2,2,4)
sns.violinplot(x='Species',y='SepalWidthCm',data=df)

"""Neural Network"""

X=df.drop('Species',axis=1)
y=df['Species']

from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

df['Species'] = pd.Categorical(df.Species)
df['Species'] = df.Species.cat.codes
# Turn response variable into one-hot response vectory = to_categorical(df.response)
y = to_categorical(df.Species)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,stratify=y,random_state=123)

model=Sequential()
model.add(Dense(100,activation='relu',input_shape=(4,)))

model.add(Dense(3,activation='softmax'))

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

history=model.fit(X_train,y_train,epochs=45,validation_data=(X_test, y_test))

model.evaluate(X_test,y_test)

pred = model.predict(X_test[:10])
print(pred)

p=np.argmax(pred,axis=1)
print(p)
print(y_test[:10])

history.history['accuracy']

history.history['val_accuracy']

plt.figure()
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'])
plt.show()